# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 22:19
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.cryptocurrency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcryptocurrency',
            options={'verbose_name': 'Configuration : crypto-monnaie', 'verbose_name_plural': 'Configurations : crypto-monnaie'},
        ),
    ]
