# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.tasks', '0004_auto_20171203_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptasks',
            name='asana_project_id',
            field=models.BigIntegerField(default=None, help_text="Veuillez indiquer l'identifiant du projet Asana dans lequel vous souhaitez travailler", null=True, verbose_name='Identifiant projet Asana'),
        ),
    ]
