# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-01 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.alarm', '0002_auto_20161224_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appalarm',
            options={'verbose_name': 'Configuration : alarme', 'verbose_name_plural': 'Configurations : alarme'},
        ),
    ]
