# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-31 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boites', '0002_auto_20161224_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCoffees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de cr\xe9ation')),
                ('enabled', models.BooleanField(default=True, help_text='Indique si cette app est activ\xe9e sur votre bo\xeete', verbose_name='App activ\xe9e ?')),
                ('last_activity', models.DateTimeField(null=True, verbose_name='Derni\xe8re activit\xe9')),
                ('url', models.URLField(default='http://demo.laclef.cc/', help_text="Veuillez indiquer l'adresse de votre serveur laclef", verbose_name='URL du serveur laclef')),
                ('uid', models.CharField(help_text='Veuillez indiquer votre identifiant utilisateur', max_length=32, verbose_name='Identifiant utilisateur')),
                ('daily', models.PositiveSmallIntegerField(default=0, verbose_name="Nombre de caf\xe9s consomm\xe9s aujourd'hui")),
                ('monthly', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de caf\xe9s consomm\xe9s ce mois')),
                ('boite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Bo\xeete')),
            ],
            options={
                'verbose_name': 'Configuration : Caf\xe9s',
                'verbose_name_plural': 'Configurations : Caf\xe9s',
            },
        ),
    ]
