# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appparking',
            name='parking',
            field=models.CharField(choices=[('HFR', 'Henri Fr\xe9ville'), ('JFK', 'J.F. Kennedy'), ('POT', 'La Poterie'), ('PRE', 'Les Pr\xe9ales'), ('VU', 'Villejean-Universit\xe9')], help_text='Veuillez s\xe9lectionner votre parking', max_length=3),
        ),
    ]
