# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 08:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.parking', '0002_auto_20170618_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appparking',
            options={'verbose_name': 'Configuration : parkings', 'verbose_name_plural': 'Configurations : parkings'},
        ),
    ]
