# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 13:43
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boites', '0013_auto_20171211_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBitmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('enabled', models.BooleanField(default=True, help_text='Indique si cette app est activée sur votre boîte', verbose_name='App activée ?')),
                ('last_activity', models.DateTimeField(null=True, verbose_name='Dernière activité')),
                ('width', models.PositiveIntegerField(default=16, verbose_name="Largeur de l'icône")),
                ('height', models.PositiveIntegerField(default=16, verbose_name="Hauteur de l'icône")),
                ('boite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Boîte')),
            ],
            options={
                'verbose_name': 'Configuration : icône personnalisée',
                'verbose_name_plural': 'Configurations : icône personnalisée',
            },
        ),
        migrations.CreateModel(
            name='Bitmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.PositiveIntegerField(default=0, verbose_name="Identifiant de l'app")),
                ('bitmap', models.TextField(blank=True, default='', max_length=1024, verbose_name='Bitmap')),
            ],
            options={
                'verbose_name': 'Bitmap',
            },
        ),
    ]
