# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 08:04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.bitmap', '0002_auto_20180304_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbitmap',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Rouge'), (2, 'Vert'), (3, 'Orange')], default=1, help_text="Veuillez indiquer la couleur de l'ic\xf4ne (ne fonctionne pas avec les \xe9crans monochromes)", verbose_name='Couleur'),
        ),
    ]
