# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applikes',
            options={'verbose_name': 'Configuration : facebook likes', 'verbose_name_plural': 'Configurations : facebook likes'},
        ),
    ]
