# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 20:41
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boites', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Indique si cette app est activ\xe9e sur votre bo\xeete', verbose_name='App activ\xe9e ?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de cr\xe9ation')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Derni\xe8re activit\xe9')),
                ('parcel', models.CharField(default='XX123456789FR', help_text="Veuillez saisir l'identifiant de votre colis", max_length=64, verbose_name='Identifiant du colis')),
                ('parcel_carrier', models.CharField(choices=[('chronopost', 'Chronopost'), ('colisprive', 'Colisprive'), ('colissimo', ' Colissimo'), ('dhl', 'DHL'), ('dpd', 'DPD'), ('gls', 'GLS'), ('itella', 'Itella'), ('ups', 'UPS')], default='chronopost', help_text='Veuillez indiquer le transporteur de votre colis', max_length=16, verbose_name='Transporteur')),
                ('arrival', models.DateTimeField(default=None, null=True, verbose_name='Date de livraison')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inconnu'), (1, 'Traitement'), (2, 'En transit'), (3, 'Livr\xe9')], default=None, null=True, verbose_name='Statut')),
                ('info', models.CharField(blank=True, max_length=64, null=True, verbose_name='Informations')),
                ('url', models.URLField(default=None, null=True, verbose_name='Lien vers le site du transporteur')),
                ('boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Bo\xeete')),
            ],
            options={
                'verbose_name': 'Configuration : colis',
                'verbose_name_plural': 'Configurations : colis',
            },
        ),
    ]
