# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.parcel', '0002_auto_20161203_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appparcel',
            name='last_activity',
            field=models.DateTimeField(null=True, verbose_name='Derni\xe8re activit\xe9'),
        ),
    ]
