# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 16:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.parcel', '0003_auto_20161224_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appparcel',
            name='parcel_carrier',
            field=models.CharField(choices=[('chronopost', 'Chronopost'), ('colisprive', 'Colis priv\xe9'), ('colissimo', 'Colissimo'), ('dpd', 'DPD'), ('dhl', 'DHL'), ('gls', 'GLS'), ('itella', 'Itella'), ('ups', 'UPS')], default='chronopost', help_text='Veuillez indiquer le transporteur de votre colis', max_length=16, verbose_name='Transporteur'),
        ),
    ]
