# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 20:36
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boites', '0016_auto_20180708_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAirQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('enabled', models.BooleanField(default=True, help_text='Indique si cette app est activée sur votre boîte', verbose_name='App activée ?')),
                ('last_activity', models.DateTimeField(null=True, verbose_name='Dernière activité')),
                ('aqi_today', models.PositiveSmallIntegerField(default=0, verbose_name="Qualité de l'air pour aujourd'hui")),
                ('boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Boîte')),
            ],
            options={
                'verbose_name_plural': "Configurations : qualité de l'air",
                'verbose_name': "Configuration : qualité de l'air",
            },
        ),
    ]
