# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-26 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.luftdaten', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appluftdaten',
            options={'verbose_name': 'Configuration : sensor.community', 'verbose_name_plural': 'Configurations : sensor.community'},
        ),
        migrations.AlterField(
            model_name='appluftdaten',
            name='sensor',
            field=models.CharField(default='11034', help_text="Veuillez saisir l'identifiant de votre capteur Sensor.Community", max_length=32, verbose_name='Identifiant du capteur Sensor.Community'),
        ),
    ]
