# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.tasks', '0003_auto_20161030_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptasks',
            name='asana_personal_access_token',
            field=models.CharField(default=None, help_text="Veuillez indiquer votre cl\xe9 d'API personnelle Asana (Personal Access Token)", max_length=64, null=True, verbose_name="Cl\xe9 d'API Asana"),
        ),
    ]
