# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boites', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Indique si cette app est activ\xe9e sur votre bo\xeete', verbose_name='App activ\xe9e ?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de cr\xe9ation')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Derni\xe8re activit\xe9')),
                ('ics_url', models.CharField(default=None, help_text="Veuillez indiquer l'adresse de votre calendrier .ics", max_length=256, null=True, verbose_name='URL du calendrier ics')),
                ('dtstart', models.CharField(default=None, max_length=5, null=True, verbose_name='Heure du prochain rendez-vous')),
                ('summary', models.CharField(default=None, max_length=256, null=True, verbose_name='Intitul\xe9 du prochain rendez-vous')),
                ('boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Bo\xeete')),
            ],
            options={
                'verbose_name': 'Configuration : calendrier',
                'verbose_name_plural': 'Configurations : calendrier',
            },
        ),
    ]
