# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcalendar',
            options={'verbose_name': 'Configuration : calendrier', 'verbose_name_plural': 'Configurations : calendrier'},
        ),
    ]
