# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 19:44
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.metro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmetro',
            name='last_activity',
            field=models.DateTimeField(null=True, verbose_name='Derni\xe8re activit\xe9'),
        ),
    ]
