# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 07:11
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.metro', '0002_auto_20170113_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmetro',
            options={'verbose_name': 'Configuration : m\xe9tro', 'verbose_name_plural': 'Configurations : m\xe9tro'},
        ),
    ]
