# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 16:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.calendar', '0003_auto_20161224_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcalendar',
            name='ics_url',
            field=models.CharField(default=None, help_text="Veuillez indiquer l'adresse de votre calendrier .ics", max_length=256, null=True, verbose_name='URL du calendrier .ics'),
        ),
    ]
