# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.traffic', '0003_auto_20161224_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apptraffic',
            options={'verbose_name': 'Configuration : trafic', 'verbose_name_plural': 'Configurations : trafic'},
        ),
        migrations.AlterField(
            model_name='apptraffic',
            name='start',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='Point de d\xe9part'),
        ),
        migrations.AlterField(
            model_name='apptraffic',
            name='trajectory_name',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Itin\xe9raire'),
        ),
        migrations.AlterField(
            model_name='apptraffic',
            name='trip_duration',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Dur\xe9e'),
        ),
    ]
