# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEnergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Indique si cette app est activ\xe9e sur votre bo\xeete', verbose_name='App activ\xe9e ?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de cr\xe9ation')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Derni\xe8re activit\xe9')),
                ('url', models.URLField(default='https://emoncms.org/', verbose_name='Consommation instantan\xe9e')),
                ('power_feedid', models.PositiveSmallIntegerField(default=None, help_text='Veuillez saisir le num\xe9ro du flux li\xe9 \xe0 votre consommation instantann\xe9e (en watts)', null=True, verbose_name='Identifiant flux puissance instantan\xe9e')),
                ('kwhd_feedid', models.PositiveSmallIntegerField(default=None, help_text='Veuillez saisir le num\xe9ro du flux li\xe9 \xe0 votre consommation cumul\xe9e (en kWh/j)', null=True, verbose_name='Identifiant flux consommation cumul\xe9e')),
                ('emoncms_read_apikey', models.CharField(default=None, help_text="Veuillez indiquer votre cl\xe9 d'API emoncms (lecture seule)", max_length=32, null=True, verbose_name="Cl\xe9 d'API emoncms")),
                ('power', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Consommation instantan\xe9e')),
                ('day0', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Consommation j-6 (en kWh)')),
                ('day1', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Consommation j-5 (en kWh)')),
                ('day2', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Consommation j-4 (en kWh)')),
                ('day3', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Consommation j-3 (en kWh)')),
                ('day4', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Consommation j-2 (en kWh)')),
                ('day5', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Consommation hier (en kWh)')),
                ('day6', models.PositiveSmallIntegerField(default=None, null=True, verbose_name="Consommation aujourd'hui (en kWh)")),
                ('boite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Bo\xeete')),
            ],
            options={
                'verbose_name': 'Configuration : \xc9nergie',
                'verbose_name_plural': 'Configurations : \xc9nergie',
            },
        ),
    ]
