# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.energy', '0002_auto_20170113_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appenergy',
            options={'verbose_name': 'Configuration : \xe9nergie', 'verbose_name_plural': 'Configurations : \xe9nergie'},
        ),
    ]
