# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 08:04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.energy', '0004_auto_20180304_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appenergy',
            name='kwhd_feedid',
            field=models.PositiveIntegerField(default=None, help_text='Veuillez saisir le num\xe9ro du flux li\xe9 \xe0 votre consommation cumul\xe9e (en kWh/j)', null=True, verbose_name='Identifiant flux consommation cumul\xe9e'),
        ),
        migrations.AlterField(
            model_name='appenergy',
            name='power_feedid',
            field=models.PositiveIntegerField(default=None, help_text='Veuillez saisir le num\xe9ro du flux li\xe9 \xe0 votre consommation instantann\xe9e (en watts)', null=True, verbose_name='Identifiant flux puissance instantan\xe9e'),
        ),
    ]
