# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptraffic',
            name='trip_duration',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Duration'),
        ),
    ]
