# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.wifi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appwifi',
            name='preshared_key',
            field=models.CharField(max_length=128, verbose_name='Cl\xe9 de protection'),
        ),
        migrations.AlterField(
            model_name='appwifi',
            name='ssid',
            field=models.CharField(max_length=64, verbose_name='Nom du r\xe9seau'),
        ),
    ]
