# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptasks',
            name='asana_project',
            field=models.TextField(default=None, verbose_name='Projet Asana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apptasks',
            name='asana_project_id',
            field=models.CharField(default=None, help_text='Veuillez indiquer le projet Asana dans lequel vous souhaitez travailler', max_length=32, null=True, verbose_name='Identifiant projet Asana'),
        ),
    ]
