# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0002_auto_20161030_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptasks',
            name='asana_project',
        ),
        migrations.AlterField(
            model_name='apptasks',
            name='asana_project_id',
            field=models.PositiveIntegerField(default=None, help_text="Veuillez indiquer l'identifiant du projet Asana dans lequel vous souhaitez travailler", null=True, verbose_name='Identifiant projet Asana'),
        ),
    ]
