# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boites', '0002_auto_20161224_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de cr\xe9ation')),
                ('enabled', models.BooleanField(default=True, help_text='Indique si cette app est activ\xe9e sur votre bo\xeete', verbose_name='App activ\xe9e ?')),
                ('last_activity', models.DateTimeField(null=True, verbose_name='Derni\xe8re activit\xe9')),
                ('icon', models.CharField(max_length=64, verbose_name='Nom du r\xe9seau')),
                ('message', models.TextField(blank=True, default='', help_text='Veuillez indiquer le message pour cette app', max_length=140, verbose_name='Message personnalis\xe9')),
                ('boite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Bo\xeete')),
            ],
            options={
                'verbose_name': 'Configuration : Affichage personnalis\xe9',
                'verbose_name_plural': 'Configurations : Affichage personnalis\xe9',
            },
        ),
    ]
