# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcustom',
            options={'verbose_name': 'Configuration : App personnalis\xe9e', 'verbose_name_plural': 'Configurations : App personnalis\xe9e'},
        ),
    ]
