# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boites', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Indique si cette app est activ\xe9e sur votre bo\xeete', verbose_name='App activ\xe9e ?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de cr\xe9ation')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Derni\xe8re activit\xe9')),
                ('stop', models.PositiveSmallIntegerField(default=None, help_text="Veuillez saisir l'identifiant Timeo de votre arr\xeat de bus", null=True, verbose_name='Arr\xeat')),
                ('route0', models.CharField(default=None, max_length=4, null=True, verbose_name='Prochain bus')),
                ('departure0', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Dans')),
                ('route1', models.CharField(default=None, max_length=4, null=True, verbose_name='Bus suivant')),
                ('departure1', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Dans')),
                ('boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Bo\xeete')),
            ],
            options={
                'verbose_name': 'Configuration : bus',
                'verbose_name_plural': 'Configurations : bus',
            },
        ),
    ]
