# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boites', '0011_tile_brightness'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('enabled', models.BooleanField(default=True, help_text='Indique si cette app est activée sur votre boîte', verbose_name='App activée ?')),
                ('last_activity', models.DateTimeField(null=True, verbose_name='Dernière activité')),
                ('url', models.URLField(default='http://api.tom.tools/hits', help_text="Veuillez indiquer l'adresse de la ressource que vous souhaitez atteindre", verbose_name='URL de la ressource JSON')),
                ('json_path', models.CharField(help_text="Veuillez indiquer le chemin de l'élément json (exemple: article.title)", max_length=64, verbose_name="Chemin de l'élément JSON (JSON Path)")),
                ('data', models.CharField(max_length=32, verbose_name="Chemin de l'élément JSON (JSON Path)")),
                ('boite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Boîte')),
            ],
            options={
                'verbose_name_plural': 'Configurations : données',
                'verbose_name': 'Configuration : données',
            },
        ),
    ]
