# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 15:55
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='json',
            field=models.TextField(blank=True, null=True, verbose_name='Dernière version de la ressource JSON'),
        ),
    ]
