# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.data', '0002_appdata_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='json_path',
            field=models.CharField(help_text="Veuillez indiquer le chemin de l'élément json (exemple: articles[0].title)", max_length=64, verbose_name="Chemin de l'élément JSON (JSON Path)"),
        ),
    ]
