# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.data', '0004_auto_20180304_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdata',
            name='append',
            field=models.CharField(blank=True, default='', help_text='Veuillez indiquer un texte que vous aimeriez voir apparaître après la donnée (une unité par exemple)', max_length=16, verbose_name='Texte concaténé à la donnée'),
        ),
        migrations.AddField(
            model_name='appdata',
            name='prepend',
            field=models.CharField(blank=True, default='', help_text='Veuillez indiquer un texte que vous aimeriez voir apparaître avant la donnée', max_length=16, verbose_name='Texte précédent la donnée'),
        ),
    ]
