# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.data', '0005_auto_20181115_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdata',
            name='append',
            field=models.CharField(blank=True, default='', help_text='Veuillez indiquer un texte que vous aimeriez voir apparaître après la donnée (une unité par exemple)', max_length=16, verbose_name='Texte suivant la donnée'),
        ),
        migrations.AlterField(
            model_name='appdata',
            name='prepend',
            field=models.CharField(blank=True, default='', help_text='Veuillez indiquer un texte que vous aimeriez voir apparaître avant la donnée', max_length=16, verbose_name='Texte précédant la donnée'),
        ),
    ]
