# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appalarm',
            name='boite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Bo\xeete'),
        ),
        migrations.AlterField(
            model_name='appalarm',
            name='last_activity',
            field=models.DateTimeField(null=True, verbose_name='Derni\xe8re activit\xe9'),
        ),
    ]
