# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boites', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Indique si cette app est activ\xe9e sur votre bo\xeete', verbose_name='App activ\xe9e ?')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de cr\xe9ation')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Derni\xe8re activit\xe9')),
                ('city_name', models.CharField(default='Paris', help_text='Veuillez saisir la ville o\xf9 se trouve votre bo\xeete', max_length=64, verbose_name='Ville')),
                ('temperature_now', models.PositiveSmallIntegerField(null=True, verbose_name='Temp\xe9rature actuelle')),
                ('humidity_now', models.PositiveSmallIntegerField(null=True, verbose_name='Humidit\xe9 actuelle')),
                ('icon_now', models.PositiveSmallIntegerField(choices=[(0, 'Temps clair'), (1, 'Nuages'), (2, 'Pluie'), (3, 'Brouillard'), (4, 'Neige')], default=1, verbose_name='Ic\xf4ne')),
                ('boite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Bo\xeete')),
            ],
            options={
                'verbose_name': 'Configuration : m\xe9t\xe9o',
                'verbose_name_plural': 'Configurations : m\xe9t\xe9o',
            },
        ),
    ]
