# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.custom', '0002_auto_20170310_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcustom',
            options={'verbose_name': 'Configuration : app personnalis\xe9e', 'verbose_name_plural': 'Configurations : app personnalis\xe9e'},
        ),
        migrations.AlterField(
            model_name='appcustom',
            name='icon',
            field=models.TextField(blank=True, default='', help_text='Veuillez indiquer le message pour cette app', max_length=1024, verbose_name='Ic\xf4ne'),
        ),
    ]
