# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.custom', '0005_auto_20170801_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitmap', models.TextField(blank=True, default='', max_length=1024, verbose_name='Bitmap')),
            ],
            options={
                'verbose_name': 'Bitmap',
            },
        ),
        migrations.RemoveField(
            model_name='appcustom',
            name='bitmap0',
        ),
        migrations.RemoveField(
            model_name='appcustom',
            name='bitmap1',
        ),
        migrations.RemoveField(
            model_name='appcustom',
            name='bitmap2',
        ),
        migrations.RemoveField(
            model_name='appcustom',
            name='bitmap3',
        ),
        migrations.RemoveField(
            model_name='appcustom',
            name='bitmap4',
        ),
    ]
