# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.custom', '0006_auto_20170804_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitmap',
            name='app_id',
            field=models.PositiveIntegerField(default=0, verbose_name="Identifiant de l'app"),
        ),
    ]
