# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-14 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.weather', '0004_auto_20180304_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appweather',
            name='temperature_now',
            field=models.SmallIntegerField(null=True, verbose_name='Température actuelle'),
        ),
    ]
