# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boite',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes', verbose_name='QR code'),
        ),
    ]
