# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boite',
            name='api_key',
            field=models.CharField(default=b'c33131a0', max_length=8, verbose_name="Cl\xe9 d'API"),
        ),
    ]
