# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0002_boite_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boite',
            name='qrcode',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='boites', verbose_name='QR code'),
            preserve_default=False,
        ),
    ]
