# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('boites', '0003_tile_tileapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tile',
            options={'verbose_name': 'Tuile', 'verbose_name_plural': 'Tuiles'},
        ),
        migrations.AddField(
            model_name='tileapp',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tileapp',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
