# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0005_auto_20161013_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boite',
            name='api_key',
            field=models.CharField(default=b'fc76fc96', max_length=8, verbose_name="Cl\xe9 d'API"),
        ),
    ]
