# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 04:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0006_auto_20170730_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileapp',
            name='x',
            field=models.SmallIntegerField(default=0, help_text="Veuillez indiquer la position en x de l'app sur la tuile (en pixels)", verbose_name='Position x'),
        ),
        migrations.AlterField(
            model_name='tileapp',
            name='y',
            field=models.SmallIntegerField(default=0, help_text="Veuillez indiquer la position en y de l'app sur la tuile (en pixels)", verbose_name='Position y'),
        ),
    ]
