# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0006_auto_20161014_1115'),
        ('boites', '0006_auto_20161014_1606'),
    ]

    operations = [
    ]
