# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0007_merge_20161014_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boite',
            name='api_key',
            field=models.CharField(default=b'dfcf7bfe', max_length=8, verbose_name="Cl\xe9 d'API"),
        ),
    ]
