# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0008_auto_20161017_1954'),
        ('boites', '0008_auto_20161017_2147'),
    ]

    operations = [
    ]
