# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 09:31
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0010_remove_pushbutton_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='brightness',
            field=models.PositiveSmallIntegerField(default=15, help_text='Veuillez saisir la luminosité souhaitée pour cette tuile', validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Luminosité de la tuile'),
        ),
    ]
