# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0012_tile_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='transition',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aucune'), (1, 'Fondu'), (2, 'Défilement ←'), (3, 'Défilement →'), (4, 'Défilement ↑'), (5, 'Défilement ↓')], default=0, help_text='Veuillez sélectionner la transition que vous souhaitez pour passer à la prochaine tuile', verbose_name='Transition'),
        ),
    ]
