# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 08:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0014_auto_20180527_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boite',
            name='screen',
            field=models.PositiveSmallIntegerField(choices=[(0, '\xc9cran monochrome 32\xd78'), (1, '\xc9cran monochrome 32\xd716'), (2, '\xc9cran bicolore 32\xd716')], default=1, help_text="Veuillez s\xe9lectionner l'\xe9cran qui compose votre bo\xeete", verbose_name="Type d'\xe9cran"),
        ),
        migrations.AlterField(
            model_name='boite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='pushbutton',
            name='boite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boites.Boite', verbose_name='Bo\xeete'),
        ),
    ]
