# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boites', '0015_auto_20180628_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='boite',
            name='sleep_time',
            field=models.TimeField(blank=True, default=None, help_text='Spécifiez une heure pour le début du mode veille (laissez vide si toujours allumée)', null=True, verbose_name='Début du mode veille'),
        ),
        migrations.AddField(
            model_name='boite',
            name='wake_time',
            field=models.TimeField(blank=True, default=None, help_text='Spécifiez une heure pour le fin du mode veille (laissez vide si toujours allumée)', null=True, verbose_name='Fin du mode veille'),
        ),
        migrations.AlterField(
            model_name='tileapp',
            name='tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile_apps', to='boites.Tile', verbose_name='Tuile'),
        ),
    ]
