# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-01 13:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.bus', '0003_auto_20161224_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appbus',
            name='stop_name',
        ),
    ]
