# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 08:04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboite.apps.bus', '0005_auto_20180304_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbus',
            name='stop',
            field=models.PositiveSmallIntegerField(default=None, help_text='Veuillez saisir le nom de votre arr\xeat de bus', null=True, verbose_name='Arr\xeat'),
        ),
    ]
